export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const CREATE_TEACHER = 'CREATE_TEACHER';
export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS';
export const CREATE_TEACHER_FAILED = 'CREATE_TEACHER_FAILED';

export const SET_PHONE = 'SET_PHONE';
export const SET_PHONE_SUCCESS = 'SET_PHONE_SUCCESS';
export const SET_PHONE_FAILED = 'SET_PHONE_FAILED';

export const UPDATE_PHONE = 'UPDATE_PHONE';
export const UPDATE_PHONE_SUCCESS = 'UPDATE_PHONE_SUCCESS';
export const UPDATE_PHONE_FAILED = 'UPDATE_PHONE_FAILED';

export const VERIFY_TOKEN = 'VERIFY_TOKEN';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAILED = 'VERIFY_TOKEN_FAILED';

export const RESEND_TOKEN = 'RESEND_TOKEN';
export const RESEND_TOKEN_SUCCESS = 'RESEND_TOKEN_SUCCESS';
export const RESEND_TOKEN_FAILED = 'RESEND_TOKEN_FAILED';

export const SAVE_USER = 'SAVE_USER';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAILED = 'SAVE_USER_FAILED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_FAILED = 'RECOVER_PASSWORD_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const GET_GOOGLEACCOUNT = 'GET_GOOGLEACCOUNT';
export const GET_GOOGLEACCOUNT_SUCCESS = 'GET_GOOGLEACCOUNT_SUCCESS';
export const GET_GOOGLEACCOUNT_FAILED = 'GET_GOOGLEACCOUNT_FAILED';

export const REGISTER_GOOGLEACCOUNT = 'REGISTER_GOOGLEACCOUNT';
export const REGISTER_GOOGLEACCOUNT_SUCCESS = 'REGISTER_GOOGLEACCOUNT_SUCCESS';
export const REGISTER_GOOGLEACCOUNT_FAILED = 'REGISTER_GOOGLEACCOUNT_FAILED';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';

export const NOTIFICATION_WORK = 'NOTIFICATION_WORK';
export const NOTIFICATION_WORK_SUCCESS = 'NOTIFICATION_WORK_SUCCESS';
export const NOTIFICATION_WORK_FAILED = 'NOTIFICATION_WORK_FAILED';

export const EXCLUDE_NOTIFICATION = 'EXCLUDE_NOTIFICATION';
export const EXCLUDE_NOTIFICATION_SUCCESS = 'EXCLUDE_NOTIFICATION_SUCCESS';
export const EXCLUDE_NOTIFICATION_FAILED = 'EXCLUDE_NOTIFICATION_FAILED';

export const INTEGRATE_NOTIFICATION = 'INTEGRATE_NOTIFICATION';
export const INTEGRATE_NOTIFICATION_SUCCESS = 'INTEGRATE_NOTIFICATION_SUCCESS';
export const INTEGRATE_NOTIFICATION_FAILED = 'INTEGRATE_NOTIFICATION_FAILED';



